[theme]
primaryColor = "#008139"     
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
# .streamlit/config.toml
[server]
maxUploadSize = 200
fileWatcherType = "none"
